{% set name = "astrocats" %}
{% set version = "0.3.30" %}
{% set sha256 = "04f1445c4642b25f48bdcd6cb406a635d1d28adb902587e458e01f271bc2e587" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - ads
    - astropy
    - astroquery
    - beautifulsoup4
    - bokeh
    - future
    - gitdb2
    - gitpython
    - inflect
    - keyring
    - palettable
    - psutil
    - seaborn
    - tqdm
    - tweepy
  run:
    - python
    - ads
    - astropy
    - astroquery
    - beautifulsoup4
    - bokeh
    - future
    - gitdb2
    - gitpython
    - inflect
    - keyring
    - palettable
    - psutil
    - seaborn
    - tqdm
    - tweepy

test:
  imports:
    - astrocats

about:
  home: http://github.com/astrocatalogs/astrocats
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Open astronomy catalogs'

  description: |
    astrocats enables astronomers to construct their own curated catalogs
    of astronomical data with the intention of producing shareable catalogs
    of that data in human-readable formats
  doc_url: https://github.com/astrocatalogs/astrocats
  dev_url: https://github.com/astrocatalogs/astrocats

extra:
  recipe-maintainers:
    - guillochon
    - lzkelley
    - pkgw
